import type { NextPage } from "next";
import Head from "next/head";

import { useGetSWR } from "~/hook";

const Home: NextPage = () => {
  const { isLoading, isError, data } = useGetSWR("/employee");
  console.info("isLoading", isLoading);
  console.info("isError", isError);
  console.info("data", data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

// eslint-disable-next-line import/no-default-export
export default Home;
