import type { NextPage } from "next";
import Head from "next/head";

import { RootPage as Body } from "~/component/page/Root";

const RootPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Body />
    </>
  );
};

// eslint-disable-next-line import/no-default-export
export default RootPage;
