import type { NextPage } from "next";
import Head from "next/head";

import { RootPage } from "~/component/page/Root";

const Root: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RootPage />
    </div>
  );
};

// eslint-disable-next-line import/no-default-export
export default Root;
